version: '3.8'

services:
  db-taskflow:
    image: postgres:15-alpine
    container_name: couplecalendar_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=TaskFlowDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: