using CoupleCalendar.Application.DTOs;
using CoupleCalendar.Core.Entities;
using CoupleCalendar.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoupleCalendar.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class EventsController : ControllerBase
{
    private readonly IEventRepository _repository; // No more Entity Framework here!

    public EventsController(IEventRepository repository)
    {
        _repository = repository;
    }

    [HttpPost]
    public async Task<IActionResult> CreateEvent([FromBody] CreateEventDto requestDto)
    {
        // 1. Mapping: Convert DTO (Input) to Entity (Database model)
        var newEvent = new CalendarEvent
        {
            Title = requestDto.Title,
            StartDate = requestDto.StartDate,
            EndDate = requestDto.EndDate,
            Owner = requestDto.Owner,
            Type = requestDto.Type
            // Note: 'Id' and 'CreatedAt' are automatically generated by the CalendarEvent class
        };

        // 2. Save to Database
        await _repository.AddAsync(newEvent);

        // 3. Return success response
        return Ok(newEvent);
    }

    [HttpGet]
    public async Task<IActionResult> GetAllEvents()
    {
        // We get the raw data from the repository
        var eventsFromDb = await _repository.GetAllAsync();

        // We map it to the DTOs
        var response = eventsFromDb.Select(e => new EventResponseDto
        {
            Id = e.Id,
            Title = e.Title,
            StartDate = e.StartDate,
            EndDate = e.EndDate,
            Owner = e.Owner,
            Type = e.Type.ToString()
        });

        return Ok(response);
    }
}